services:
  bot:
    build: .
    env_file:
      - bot.env
    environment:
      WEB_SERVER_PORT: "8080"
    ports:
      - "9999:8080"
  postgres:
    image: postgres:16
    profiles:
      - infra
    environment:
      - POSTGRES_USER=split_my_check
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=split_my_check
    ports:
      - "5432:5432"
    volumes:
      # map postgres data to local folder
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
